site_name: CEU scientific meetings
nav:
  - "": README.md
  - Chronicle:
    - COVID-19.md
    - Cambridge-Baker-Joint-Symposium.md
    - 2021.md
    - 2020.md
  - HDR(UK): HDR.md
  - Schedules: schedules.md
  - Zoom: zoom.md
  - Resources: resources.md
  - Channels: channels.md
  - Talks: talks.md
theme:
    name: mkdocs
    nav_style: dark
    highlightjs: true
    hljs_languages:
        - Bash
        - HTML
        - Java
        - JavaScript
        - Perl
        - Python
        - R
        - rust
        - yaml
plugins:
    - search
    - mermaid2
markdown_extensions:
  - attr_list
  - meta
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
