site_name: CEU scientific meetings
nav:
  - "": README.md
  - Chronicle:
    - 2024: 2024.md
    - 2023: 2023.md
    - 2022: 2022.md
    - 2021: 2021.md
    - 2020: 2020.md
    - mhs: mhs.md
    - COVID-19: COVID-19.md
    - cbjs: Cambridge-Baker-Joint-Symposium.md
  - HDR(UK): HDR-UK.md
  - Schedules: schedules.md
  - Resources:
    - CEU: CEU.md
    - DPHPC: DPHPC.md
    - School: School.md
    - University: University.md
    - University Again:
      - Flask: Flask.md
      - c6: c6.md
      - web: web.md
  - Channels: channels.md
  - Talks: talks.md
theme:
    name: mkdocs
    nav_style: dark
    highlightjs: true
    hljs_languages:
        - Bash
        - HTML
        - Java
        - JavaScript
        - Perl
        - Python
        - R
        - rust
        - yaml
extra_css:
  - stylesheets/extra.css
plugins:
    - search
    - mermaid2
markdown_extensions:
  - attr_list
  - footnotes
  - meta
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
