site_name: CEU-scientific-meetings
nav:
  - Contents: contents.md
  - HDR(UK): HDR.md
  - Schedules: schedules.md
  - COVID-19: COVID-19.md
  - Zoom: zoom.md
  - Online facilities: online.md
  - Media: media.md
  - External evets: external_talks.md
  - Chronological Information:
    - 2021.md
    - 2020.md
theme:
    name: mkdocs
    nav_style: dark
    highlightjs: true
    hljs_languages:
        - Bash
        - HTML
        - Java
        - JavaScript
        - Perl
        - Python
        - R
        - rust
        - yaml
plugins:
    - search
    - mermaid2
markdown_extensions:
  - attr_list
  - meta
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
